import type { ContentComponent, Placement, WebsitePage } from "./types";

const updatedAt = "2026-07-01 00:00";

export const components: ContentComponent[] = [
  { id: "brand.title", title: "主題名稱", zh: "Big Bang! Futures!", en: "Big Bang! Futures!", status: "done", kind: "title", scope: "shared", updatedAt },
  { id: "brand.slogan.zh", title: "中文標語", zh: "未來將不再以低語傳遞，而是以爆炸式發生。", en: "The future doesn't whisper; it bangs!", status: "done", kind: "slogan", scope: "shared", updatedAt },
  { id: "brand.slogan.en", title: "英文標語", zh: "The future doesn't whisper; it bangs!", en: "未來將不再以低語傳遞，而是以爆炸式發生。", status: "done", kind: "slogan", scope: "shared", updatedAt },
  { id: "brand.date.range", title: "活動日期", zh: "2026.08.03–08.06", en: "2026.08.03–08.06", status: "done", kind: "meta", scope: "shared", updatedAt },
  { id: "brand.concept.zh", title: "主題概念中文", zh: "源自宇宙霹靂般的起始瞬間，象徵無數未來的誕生。\n邀請來自不同領域、文化與背景的人們，帶著各自的未來觀相遇，\n讓每一次碰撞，都成為下一次 Big Bang!", en: "Inspired by the universe's first explosive moment, where countless futures are born.\nDifferent visions of the future meet here.\nDifferent minds collide.\nEvery collision sparks the next Big Bang!", status: "done", kind: "paragraph", scope: "shared", updatedAt },
  { id: "brand.concept.en", title: "主題概念英文", zh: "Inspired by the universe's first explosive moment, where countless futures are born.\nDifferent visions of the future meet here.\nDifferent minds collide.\nEvery collision sparks the next Big Bang!", en: "源自宇宙霹靂般的起始瞬間，象徵無數未來的誕生。\n邀請來自不同領域、文化與背景的人們，帶著各自的未來觀相遇，\n讓每一次碰撞，都成為下一次 Big Bang!", status: "done", kind: "paragraph", scope: "shared", updatedAt },
  { id: "info.schedule.dual.zh", title: "雙場域時程中文", zh: "2026.08.05\n09:30 - 16:40 Futures Stage, 三創生活 5F\n(Keynotes • Panels • International Exchange)\n\n15:30 - 20:00 Big Bang! Night Market, 三創生活 12F\n(Demo • Poster • Performances • Food • Market)", en: "09:30 - 16:40 Futures Stage, Syntrend Creative Park 5F\n(Keynotes • Panels • International Exchange)\n\n15:30 - 20:00 Big Bang! Night Market, Syntrend Creative Park 12F\n(Demo • Poster • Performances • Food • Market)", status: "done", kind: "section", scope: "shared", updatedAt },
  { id: "info.schedule.dual.en", title: "雙場域時程英文", zh: "2026.08.05\n09:30 - 16:40 Futures Stage, Syntrend Creative Park 5F\n(Keynotes • Panels • International Exchange)\n\n15:30 - 20:00 Big Bang! Night Market, Syntrend Creative Park 12F\n(Demo • Poster • Performances • Food • Market)", en: "09:30 - 16:40 Futures Stage, 三創生活 5F\n(Keynotes • Panels • International Exchange)\n\n15:30 - 20:00 Big Bang! Night Market, 三創生活 12F\n(Demo • Poster • Performances • Food • Market)", status: "done", kind: "section", scope: "shared", updatedAt },
  { id: "logo.group", title: "Logo 組合", zh: "四個活動單位 Logo：晶創人文、TAICHI、APMAR、ISAT\n主辦單位：國立臺灣科技大學、國立臺灣大學、國立臺北科技大學\n贊助單位：美國在台協會、AIC、國科會工程科技推展中心", en: "Four event unit logos: Humanities x IC, TAICHI, APMAR, ISAT\nOrganizers: National Taiwan University of Science and Technology, National Taiwan University, National Taipei University of Technology\nSponsors: AIT, AIC, NSTC Center for Engineering and Technology", status: "done", kind: "meta", scope: "shared", updatedAt },
  { id: "org.humxic", title: "晶創人文", zh: "國科會人文處推動晶創人文計畫，從人文需求出發，讓電腦科技與藝術跨界碰撞，落實人文驅動晶片創新的理念。本計畫今年主打晶創DIY，聯合 APMAR、TAICHI、ISAT 研討會及 OpenHCI 學生工作坊盛大舉辦，期盼打破專業門檻，透過前衛的互動科技，讓社會大眾親身感受人文與科技交織共同勾勒未來生活的新型態應用。", en: "The NSTC's Department of Humanities and Social Sciences initiates the Humanities x IC program, fusing computer technology with art to realize the vision of humanities driving chip innovation. The main theme for this year, Democratizing Chip Innovation, is presented in collaboration with the APMAR, TAICHI, and ISAT conferences, alongside the OpenHCI student workshop, inviting the public to experience firsthand how blending humanities and technology shapes innovative applications for our future by demonstrating cutting-edge interactive technology.", status: "done", kind: "organization", scope: "shared", updatedAt },
  { id: "org.taichi", title: "TAICHI", zh: "TAICHI 致力推動人機互動研究、教育與國際交流，串聯臺灣 HCI 學術與產業社群。關注人機協作、互動科技、智慧物件、混合實境、永續設計與未來生活等重要議題。", en: "TAICHI promotes research, education, and international collaboration in Human-Computer Interaction. Exploring Human-AI Collaboration, XR, Smart Objects, Sustainable Design, and Future Living.", status: "done", kind: "organization", scope: "shared", updatedAt },
  { id: "org.openhci", title: "OpenHCI", zh: "OpenHCI 學生組織台灣人機互動工作坊", en: "OpenHCI (Taiwan HCI Student Workshop)", status: "done", kind: "organization", scope: "shared", updatedAt },
  { id: "org.apmar", title: "APMAR", zh: "APMAR 致力於促進亞太地區混合實境（MR）、擴增實境（AR）與延展實境（XR）領域之研究合作與學術交流，提供研究者、實務工作者及學生一個分享研究成果、交流創新想法，並與國際專家深入互動的平台。", en: "APMAR has played an important role in promoting mixed reality research and collaboration across the Asia-Pacific region. The workshop provides a friendly and focused environment for researchers, practitioners, and students to present their work, exchange ideas, and engage with experts in the field.", status: "done", kind: "organization", scope: "shared", updatedAt },
  { id: "org.isat", title: "ISAT", zh: "ISAT 致力於促進科技藝術、互動媒體、人工智慧、設計與數位文化等領域之研究合作與學術交流，提供研究者、藝術家、設計師、實務工作者及學生分享研究成果、創作實踐與創新觀點的平台，透過論文發表、作品展示、海報發表及專題論壇，促進跨領域合作，深化臺灣與國際科技藝術社群的交流與連結。", en: "ISAT is dedicated to advancing research collaboration and academic exchange in the fields of art and technology, interactive media, artificial intelligence, design, and digital culture. It provides a platform for researchers, artists, designers, practitioners, and students to share research findings, creative practices, and innovative ideas. Through paper presentations, artwork exhibitions, poster sessions, and thematic forums, ISAT fosters interdisciplinary collaboration and deepens exchanges and connections between Taiwan and the international art and technology community.", status: "done", kind: "organization", scope: "shared", updatedAt },
  { id: "venue.loading.screen", title: "螢幕展示", zh: "5F 和 12F 舞台上大螢幕 loading 畫面", en: "Main screens on 5F and 12F stages", status: "done", kind: "poster", scope: "exhibition", updatedAt },
  { id: "venue.hero.5f", title: "5F 入口主視覺", zh: "Big Bang! Futures!、標語、主題概念、主活動行程、5F 行程表、四單位 Logo", en: "Big Bang! Futures!, slogan, concept, schedule, keynote list, four logos", status: "done", kind: "hero", scope: "exhibition", updatedAt },
  { id: "venue.hero.12f", title: "12F 主視覺", zh: "Big Bang! Futures!、標語、主題概念、主活動說明、12F 行程表、四單位 Logo", en: "Big Bang! Futures!, slogan, concept, schedule, opening show, four logos", status: "done", kind: "hero", scope: "exhibition", updatedAt },
  { id: "venue.overview", title: "活動整體資訊", zh: "與 ➋ / ➌ 同版型，偏活動資訊整合，含 5F / 12F 兩場域時段與概念文。", en: "Same structure as ➋ / ➌, focusing on event overview with 5F / 12F time blocks and concept copy.", status: "done", kind: "overview", scope: "exhibition", updatedAt },
  { id: "venue.reception", title: "報到處背板", zh: "Big Bang! Futures!、Registration、四單位 Logo", en: "Big Bang! Futures!, Registration, four logos", status: "done", kind: "signage", scope: "exhibition", updatedAt },
  { id: "venue.lounge.title", title: "休息區標題", zh: "Big Bang! Futures!", en: "Big Bang! Futures!", status: "done", kind: "title", scope: "exhibition", updatedAt },
  { id: "venue.lounge.desc", title: "休息區介紹", zh: "紙箱椅是基本設計課程的重要成果，讓設計從課堂走入展場。", en: "The cardboard chair project turns classroom experiments into public seating.", status: "done", kind: "paragraph", scope: "exhibition", updatedAt },
  { id: "venue.food.title", title: "品牌名稱", zh: "老濟安 Healing Herbar", en: "Healing Herbar", status: "done", kind: "title", scope: "exhibition", updatedAt },
  { id: "venue.food.desc", title: "品牌介紹", zh: "創立於 1972 年的老濟安，傳承萬華青草巷三代草本文化，持續以創新風味詮釋臺灣青草茶。此次與 Big Bang! Futures 聯名合作，透過限定草本特調，讓在地傳統與未來想像交融，品味一場跨越世代的相遇。", en: "Founded in 1972, Healing Herbar has carried forward three generations of herbal tea craftsmanship from Taipei's Wanhua Herbal Lane, blending tradition with contemporary creativity. Created in collaboration with Big Bang! Futures, these limited-edition herbal drinks invite visitors to experience where local heritage meets future imagination.", status: "done", kind: "paragraph", scope: "exhibition", updatedAt },
  { id: "venue.performance.board", title: "表演主題", zh: "Vibe Coding Show (15:30 - 20:00)", en: "Vibe Coding Show (15:30 - 20:00)", status: "done", kind: "poster", scope: "exhibition", updatedAt },
  { id: "venue.performance.timesheet", title: "現場時刻表", zh: "Live Show Timesheet by TOPLAP NTUST\n\nTimesheet / Show name / Brief / Performer / Performer\n\nTBD ... 賴憲澤 Zec Lai", en: "Live Show Timesheet by TOPLAP NTUST\n\nTimesheet / Show name / Brief / Performer / Performer\n\nTBD ... Zec Lai", status: "done", kind: "table", scope: "exhibition", updatedAt },
  { id: "venue.interactive.market", title: "互動市集", zh: "晶創人文成果 / TAICHI / APMAR / ISAT", en: "Humanities x IC / TAICHI / APMAR / ISAT", status: "done", kind: "market", scope: "exhibition", updatedAt },
  { id: "venue.exhibitor.board", title: "參展單位介紹牌", zh: "各參展單位介紹", en: "Exhibitor intro boards", status: "done", kind: "board", scope: "exhibition", updatedAt },
  { id: "venue.map.index.guide", title: "地圖對照", zh: "地圖上的數字編號對應介紹列表", en: "Numbered map legend", status: "done", kind: "guide", scope: "exhibition", updatedAt },
];

export const exhibitionPlacements: Placement[] = [
  { id: "exhibition.1.screen", number: "➊", title: "螢幕展示", floor: "5F", area: "5F 和 12F 舞台上大螢幕 loading 畫面", refs: ["venue.loading.screen", "brand.title", "brand.slogan", "brand.date.range"] },
  { id: "exhibition.2.hero-5f", number: "➋", title: "5F 入口處螢幕主視覺牆", floor: "5F", area: "入口主視覺牆", refs: ["venue.hero.5f", "brand.title", "brand.slogan", "brand.tagline.long"] },
  { id: "exhibition.3.hero-12f", number: "➌", title: "12F 主視覺牆", floor: "12F", area: "結合報到處標示的主視覺", refs: ["venue.hero.12f", "brand.title", "brand.slogan", "brand.tagline.long"] },
  { id: "exhibition.4.overview", number: "➍", title: "活動整體資訊排版", floor: "5F", area: "活動資訊版面", refs: ["venue.overview", "brand.date.event", "info.futures.stage.desc", "info.night.market.desc"] },
  { id: "exhibition.5.reception", number: "➎", title: "5F 報到處背板", floor: "5F", area: "報到處背板", refs: ["venue.reception", "brand.title"] },
  { id: "exhibition.6.performance", number: "➏", title: "表演區背板", floor: "12F", area: "Vibe Coding Show 背板", refs: ["venue.performance.board", "venue.performance.timesheet"] },
  { id: "exhibition.7.lounge", number: "➐", title: "休息區／親子活動區背板", floor: "5F", area: "休息區與親子區", refs: ["venue.lounge.title", "venue.lounge.desc", "brand.date.range"] },
  { id: "exhibition.8.food", number: "➑", title: "飲食攤位介紹", floor: "12F", area: "飲食攤位", refs: ["venue.food.title", "venue.food.desc", "info.night.market.desc"] },
  { id: "exhibition.10.map", number: "➓", title: "展場地圖 + 互動牆", floor: "12F", area: "互動牆與地圖", refs: ["venue.map.index.guide", "venue.interactive.market", "venue.performance.timesheet"] },
  { id: "exhibition.11.exhibitors", number: "➊➊", title: "參展單位介紹牌", floor: "12F", area: "參展單位介紹牌", refs: ["venue.exhibitor.board", "org.humxic.desc", "org.taichi.desc", "org.apmar.desc", "org.isat.desc"] },
];

export const websitePages: WebsitePage[] = [
  { id: "website.home", title: "Home", refs: ["brand.title", "brand.slogan", "brand.tagline.long", "brand.date.range"] },
  { id: "website.event-info", title: "Event Info", refs: ["brand.date.event", "info.futures.stage.desc", "info.night.market.desc", "info.location.syntrend", "info.location.5f", "info.location.12f"] },
  { id: "website.schedule", title: "Schedule", refs: ["brand.date.event", "venue.performance.timesheet", "venue.interactive.market"] },
  { id: "website.organizations", title: "Organizations", refs: ["org.humxic.desc", "org.taichi.desc", "org.apmar.desc", "org.isat.desc"] },
  { id: "website.food", title: "Food Market", refs: ["venue.food.title", "venue.food.desc", "info.night.market.desc"] },
  { id: "website.performance", title: "Performance", refs: ["venue.performance.board", "venue.performance.timesheet"] },
];
